on:
  push:
    tags:
      - "*"
  
name: Create and Publish Release

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Build Package
        run: |
          npm ci
          npm run build
      - name: Zip Package
        run: |
          pushd pkg
          zip -r "../tracernz-plugin-wt21-mobiflight-cdu-${GITHUB_REF_NAME}.zip" .
          popd
      - name: Zip MobiFlight Profiles
        run: |
          pushd profiles
          zip -r "../wt21-mobiflight-cdu-profiles-${GITHUB_REF_NAME}.zip" .
          popd
      - uses: softprops/action-gh-release@v2
        with:
          files: '*.zip'
